source 'https://rubygems.org'
gem 'jekyll', '>= 2.5.3'
gem 'octopress', '>= 3.0.11'
gem 'coffee-script', '>= 2.3.0'
gem 'therubyracer', '>= 0.12.2'
group :jekyll_plugins do
  gem 'jekyll-auto-image', '>= 1.0.1'
  gem 'jekyll-redirect-from', '>= 0.6.2'
  gem 'jekyll-smartify', '>= 0.0.3'
  gem 'jekyll-tagging', '>= 1.0.1'
  gem 'jekyll-timeago', '>= 0.8.2'
  gem 'jekyll_version_plugin', '>= 1.0.2'
  gem 'liquid_pluralize', '>= 1.0.1'
  gem 'liquid_reading_time', '>= 1.1.1'
  gem 'octopress-abort-tag', '>= 1.0.2'
  gem 'octopress-asset-pipeline', '>= 2.0.5'
  gem 'octopress-codefence', '>= 1.6.1'
  gem 'octopress-comment-tag', '>= 1.0.1'
  gem 'octopress-date-format', '>= 3.0.3'
  gem 'octopress-debugger', '>= 1.0.2'
  gem 'octopress-escape-code', '>= 2.0.6'
  gem 'octopress-feeds', '>= 2.0.4'
  gem 'octopress-gist', '>= 1.3.5'
  gem 'octopress-image-tag', '>= 1.1.0'
  gem 'octopress-ink', '>= 1.1.4'
  gem 'octopress-littlefoot', '>= 1.0.2'
  gem 'octopress-markdown-tag', '>= 1.1.2'
  gem 'octopress-minify-html', '>= 1.3.0'
  gem 'octopress-pullquote-tag', '>= 1.0.1'
  gem 'octopress-quote-tag', '>= 1.0.4'
  gem 'octopress-solarized', '>= 1.1.2'
  gem 'octopress-video-tag', '>= 1.1.1'
end
group :css do
  gem 'bourbon', '>= 4.2.3'
  gem 'neat', '>= 1.7.2'
  gem 'bitters', '>= 1.0.0'
end
group :test do
  gem 'rubocop', '>=  0.15.0'
  gem 'html-proofer', '>= 2.1.0'
  gem 'scss_lint', '>= 0.33.0'
end
group :stock do
    gem 'bigdecimal', '>= 1.2.6'
    gem 'bundle', '>= 0.0.1'
    gem 'bundler', '>= 1.10.6'
    gem 'io-console', '>= 0.4.3'
    gem 'json', '>= 1.8.1'
    gem 'minitest', '>= 5.4.3'
    gem 'power_assert', '>= 0.2.2'
    gem 'psych', '>= 2.0.8'
    gem 'rake', '>= 10.4.2'
    gem 'rdoc', '>= 4.2.0'
    gem 'test-unit', '>= 3.0.8'
end
