source 'https://rubygems.org'
gem 'compass', '>= 1.0.3'
gem 'compass-html5bp', '>= 1.0.0'
gem 'font-awesome-sass', '>= 4.3.0'
gem 'rouge', '>= 1.8.0'
gem 'scss-lint', '>= 0.33.0'
gem 'coffee-script', '>= 2.3.0'
